version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis
    ports: 
      - "6379:6379"
    command: "redis-server /etc/redis.conf"
    volumes: 
      - "./data/master:/data/"
      - "./master.conf:/etc/redis.conf"
    slave:
      image: redis
      command: redis-server --slaveof redis-master 6379
      links:
        - master:redis-master
    sentinel:
      build: sentinel
      environment:
        - SENTINEL_DOWN_AFTER=5000
        - SENT INEL_FAILOVER=5000
      links:
        - master:redis-master
        - slave
      ports:
        - "26379:26379"
  
