version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis
    ports: 
      - "6379:6379"
    command: "redis-server /etc/redis.conf"
    volumes: 
      - "./data/master:/data/"
      - "./master.conf:/etc/redis.conf"

  redis-slave:
    container_name: "redis-slave"
    image: redis
    ports: 
      - "6380:6379"
    command: "redis-server /etc/redis.conf"
    volumes: 
      - "./data/slave:/data/"
      - "./slave.conf:/etc/redis.conf"

  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - redis-master:redis-master
      - redis-slave:redis-slave
    ports:
      - "26379:26379"
    
